### ISSUE TITLE
BMAB openpose hand detailer: List index out of rage

### ISSUE THREAD

**Issue by zBilalz** [portu-sim/comfyui_bmab#32]
I have tried updating Comfyui and all the custom nodes, as well as updating ONNXRuntime and checking compatibility versions, nothing seems to work.

**Error I received:**
Person 1
Hand 2
box in box result True (702, 253, 816, 479) (54, 6, 809, 1204)
box in box result True (234, 221, 348, 337) (54, 6, 809, 1204)
model_path is C:\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\yolox_l.onnx
model_path is C:\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\dw-ll_ucoco_384.onnx

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384.onnx for pose estimation
DWPose: Caching ONNXRuntime session yolox_l.onnx...
2024-07-31 21:20:48.0799849 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-07-31 21:20:48.1004758 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:895 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
DWPose: Caching ONNXRuntime session dw-ll_ucoco_384.onnx...
2024-07-31 21:20:49.0423060 [E:onnxruntime:Default, provider_bridge_ort.cc:1745 onnxruntime::TryGetProviderInfo_CUDA] D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1426 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "C:\Users\name\AppData\Local\Programs\Python\Python312\Lib\site-packages\onnxruntime\capi\onnxruntime_providers_cuda.dll"

2024-07-31 21:20:49.0626353 [W:onnxruntime:Default, onnxruntime_pybind_state.cc:895 onnxruntime::python::CreateExecutionProviderInstance] Failed to create CUDAExecutionProvider. Please reference https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html#requirementsto ensure all dependencies are met.
DWPose: Bbox 1367.31ms
!!! Exception during processing!!! list index out of range
Traceback (most recent call last):
  File "C:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\detailers.py", line 699, in process
    result, bbox_result = self.process_image(bind, bgimg, squeeze, box_threshold, text_threshold, img2img)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\detailers.py", line 661, in process_image
    bgimg, bounding_box, cbx = self.process_person(bind, bgimg, bounding_box, person, person_hand, squeeze, img2img)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\detailers.py", line 604, in process_person
    cnname = openpose.get_openpose_filenames()[0]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
 **Workflow:**
   
![afbeelding](https://github.com/user-attachments/assets/43766b10-bb7a-421a-8952-d0a8a07fd5b0)

**Comment by portu-sim** [comment]
You should download openpose controlnet from internet. and put it into model/controlnet
