### ISSUE TITLE
업데이트 이후에 갑자기 오류가 납니다.

### ISSUE THREAD

**Issue by Neytiri7** [portu-sim/comfyui_bmab#41]
```
Traceback (most recent call last):
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\__init__.py", line 6, in <module>
    from bmab import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\bmab\__init__.py", line 1, in <module>
    from bmab import nodes, serverext
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\__init__.py", line 20, in <module>
    from .fill import BMABInpaint, BMABOutpaintByRatio, BMABReframe
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\fill.py", line 2, in <module>
    import spaces
  File "W:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\spaces\__init__.py", line 10, in <module>
    from .zero.decorator import GPU
  File "W:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\spaces\zero\decorator.py", line 18, in <module>
    from .wrappers import regular_function_wrapper
  File "W:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\spaces\zero\wrappers.py", line 42, in <module>
    Process = multiprocessing.get_context('fork').Process
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "multiprocessing\context.py", line 243, in get_context
  File "multiprocessing\context.py", line 193, in get_context
ValueError: cannot find context for 'fork'

Cannot import W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab module for custom nodes: cannot find context for 'fork'
```

**Comment by Neytiri7** [comment]
챗GPT로 물어봐서 fork를 spawn로 바꿨는데, 오류가 바뀌어서, 아래 메시지가 표시되고 있습니다. 

Traceback (most recent call last):
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\__init__.py", line 6, in <module>
    from bmab import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\bmab\__init__.py", line 1, in <module>
    from bmab import nodes, serverext
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\__init__.py", line 20, in <module>
    from .fill import BMABInpaint, BMABOutpaintByRatio, BMABReframe
  File "W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\fill.py", line 4, in <module>
    from diffusers import AutoencoderKL, TCDScheduler
ImportError: cannot import name 'TCDScheduler' from 'diffusers' (W:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\diffusers\__init__.py)

Cannot import W:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab module for custom nodes: cannot import name 'TCDScheduler' from 'diffusers' (W:\SynologyDrive\ComfyUI-webui\python_embeded\Lib\site-packages\diffusers\__init__.py)

**Comment by portu-sim** [comment]
새로 들어간 기능 때문에 발생 하는 것으로 보이는데, 저도 처음 보는 것이라... 좀 확인해보겠습니다.

**Comment by portu-sim** [comment]
불필요한 의존성을 제거했습니다. 확인 해보세요.

**Comment by Neytiri7** [comment]
오류 발생한 상태에서 업데이트 해봤는데, 동일한 오류 나오고,
혹시나 지우고 다시 설치 해봤지만, 동일한 오류가 나옵니다.

**Comment by portu-sim** [comment]
diffusers 버전이 낮아서 발생하는 것 같습니다.
pip uninstall diffusers
pip install diffusers
과정을 통해서 버전을 올리셔야 할 것 같습니다.

**Comment by Neytiri7** [comment]
버전도 올렸습니다. 파이선 폴더랑 BMAB 폴더 다...
그래도 저렇게 오류가 납니다.
어디다가 버전 업을 해야 하나요?

**Comment by portu-sim** [comment]
W:\SynologyDrive\ComfyUI-webui\python_embeded\python.exe -m pip uninstall diffusers 
W:\SynologyDrive\ComfyUI-webui\python_embeded\python.exe -m pip install diffusers 
이렇게 해야합니다.
지금 실행시킨 pip는...os 전체에 적용되는 pip이고, comfyui가 사용하는 파이썬은 W:\SynologyDrive\ComfyUI-webui\python_embeded 여기에 들어있습니다. 이 둘은 완전히 다른 것입니다. 이 환경을 virtual environment 라고 합니다.

**Comment by Neytiri7** [comment]
아~ 맞다. 파이썬 환경을 생각 못하고, 그냥 하고 안된다고 하고 있었네요...
요즘 정신없이 모델 만들고 있어서, 제가 착각 했습니다.
해결 했습니다.

친절하게 대해주셔서 고맙습니다.
