### ISSUE TITLE
No module named 'diffusers.models.model_loading_utils'

### ISSUE THREAD

**Issue by Garin2-colab** [portu-sim/comfyui_bmab#42]
Hi I'm getting this error since the update.

Traceback (most recent call last):
  File "C:\AI\StabilityMatrix\Data\Packages\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_bmab\__init__.py", line 6, in <module>
    from bmab import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\AI\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_bmab\bmab\__init__.py", line 1, in <module>
    from bmab import nodes, serverext
  File "C:\AI\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\__init__.py", line 20, in <module>
    from .fill import BMABInpaint, BMABOutpaintByRatio, BMABReframe
  File "C:\AI\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\fill.py", line 4, in <module>
    from diffusers.models.model_loading_utils import load_state_dict
ModuleNotFoundError: No module named 'diffusers.models.model_loading_utils'

Cannot import C:\AI\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_bmab module for custom nodes: No module named 'diffusers.models.model_loading_utils'

**Comment by xujiamingtxwd123** [comment]
the same problem

**Comment by portu-sim** [comment]
please. update diffusers,
pip uninstall diffusers
pip install diffusers

**Comment by saberzaid** [comment]
please. update diffusers,
pip uninstall diffusers
pip install diffusers

this not fix my problem 


Traceback (most recent call last):
  File "C:\Ai\Data\Packages\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Ai\Data\Packages\ComfyUI\custom_nodes\ComfyUI-ELLA-wrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Ai\Data\Packages\ComfyUI\custom_nodes\ComfyUI-ELLA-wrapper\nodes.py", line 28, in <module>
    raise ImportError("Diffusers version too old. Please update to 0.26.0 minimum.")
ImportError: Diffusers version too old. Please update to 0.26.0 minimum.


i did uninstall and install again , same problem

**Comment by portu-sim** [comment]
The pip command must be run in your python virtual environment.
